API enhancement
eptastellar/Orbit pull request #11
Opened 2024-02-11 21:20 UTC by mzyxnuel

## Added routes:

- /u 
  - /settings
  - user basic information /:username
  - fetch user posts with pagination  
- /home
  - fetch friends posts with pagination  
- /p
  - add post
- /c
  - roots comments pagination
  - leaf comments pagination
- /l --> likes
- /cron --> cron jobs
- [...catchall] --> 404 route

## Fixed routes:
- /auth

2024-02-11 21:23 UTC, mzyxnuel commented
LGTM

2024-02-11 21:43 UTC, 74C17N3P7UN3 approved these changes

2024-02-12 12:46 UTC, TheInfernalNick requested changes

2024-02-12 12:46 UTC, TheInfernalNick commented on web/src/algorithms/supernova.ts
> +   const neo4j: Session = neoStart() //TODO: @TheInfernalNick add neoClose for each transaction
togliere il todo

2024-02-12 12:46 UTC, TheInfernalNick commented on web/src/assets/interests.ts
Bisogna rimettere il vecchio file

2024-02-12 12:46 UTC, TheInfernalNick commented on web/src/routes/auth/sign-up/validate/index.ts
A cosa ci serve questa route se facciamo già tutti i check in sign-up?

2024-02-12 12:55 UTC, mzyxnuel commented on web/src/assets/interests.ts
va bene questo

2024-02-12 12:56 UTC, mzyxnuel commented on web/src/routes/auth/sign-up/validate/index.ts
frontend, validazione dei dati durante il form, nella pagina di username e bday

2024-02-12 13:00 UTC, mzyxnuel commented on web/src/algorithms/supernova.ts
> +   const neo4j: Session = neoStart() //TODO: @TheInfernalNick add neoClose for each transaction
quando toccherai supernova lo levi

2024-02-12 13:03 UTC, TheInfernalNick approved these changes

2024-02-12 13:32 UTC, merged